# Generated by Django 4.2.6 on 2024-02-22 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing_bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_nacimiento',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField(default='0000-00-00')),
                ('situacion', models.CharField(choices=[('Prospecto', 'Prospecto'), ('Apertura', 'Apertura'), ('Seguimiento', 'Seguimiento'), ('Otra', 'Otra')], max_length=20, null=True)),
                ('comentario', models.TextField(null=True)),
                ('arvhivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunion_cliente', to='landing_bd.cliente')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunion_ejecutivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
