# Generated by Django 4.2.6 on 2024-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0004_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='familia',
            name='sociedades',
            field=models.ManyToManyField(to='landing_bd.sociedad'),
        ),
    ]
