# Generated by Django 4.2.6 on 2024-03-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0005_sociedad_alter_familia_nombre_familia_sociedades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='sociedades',
            new_name='entidades',
        ),
    ]
