# Generated by Django 5.0.3 on 2024-03-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0007_remove_familia_entidades_alter_familia_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociedades_familia', to='landing_bd.familia')),
            ],
        ),
    ]
