# Generated by Django 5.0.3 on 2024-03-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0009_alter_reuniones_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniones',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/archivos/'),
        ),
    ]
