# Generated by Django 5.0.3 on 2024-04-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0010_alter_reuniones_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
