# Generated by Django 5.0.3 on 2024-04-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0012_alter_cliente_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
