# Generated by Django 5.0.3 on 2024-04-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0013_alter_cliente_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniones',
            name='archivo',
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='media/archivos/')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='landing_bd.reuniones')),
            ],
        ),
    ]
