# Generated by Django 5.0.3 on 2024-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_bd', '0014_remove_reuniones_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniones',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/archivos/'),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
